# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ab63863f4963faad3d6114481026a782cef89e58db196a58b9b2c4970d7c8cb092a180b48475a2133fc2aa9a5bc33863b20d87d1680696f1915a491552747c

test:
  secret_key_base: e86e22a7998207fc2da7675d9fa0f84bfcdd81d2c9b350c7a54d5903499a935fb5963982a0e5e21ecb0c9dc850c3599f9373ae055ae86321f83eb4afc63ec66c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
